apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  path: ./staging
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: gowebserver
  namespace: apps
spec:
  filterTags:
    extract: $ts
    pattern: ^staging-[a-f0-9]+-(?P<ts>[0-9]+)